language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'

branches:
    only:
        - master

before_install:
    - composer install

script:
    - ./vendor/phpunit/phpunit/phpunit --configuration ./phpunit.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
